module.exports.Staffs = require('./Staffs')
module.exports.Posts = require('./Posts')
module.exports.Accounts = require('./Accounts')
module.exports.Mail = require('./Mail')
module.exports.Appointments = require('./Appointments')