module.exports.Staffs = require('./Staffs')
module.exports.Posts = require('./Posts')
module.exports.Q_and_as = require('./Q_and_as')
module.exports.Accounts = require('./Accounts')
module.exports.Mail = require('./Mail')
module.exports.Appointments = require('./Appointments')
module.exports.ChatBot = require('./ChatBot')